train: ./dataset/images/train  # Path to training images
val: ./dataset/images/val      # Path to validation images
test: ./dataset/images/test    # Path to test images

nc: 1  # Number of classes
names: ['']  # Class names
